"""update work_shop

Revision ID: 0708b582fe50
Revises: 579b8737e664
Create Date: 2025-10-10 11:45:23.338001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0708b582fe50'
down_revision: Union[str, Sequence[str], None] = '579b8737e664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_shop', sa.Column('username', sa.String(), server_default='', nullable=False), schema='work_shop')
    op.drop_column('work_shop', 'login', schema='work_shop')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_shop', sa.Column('login', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False), schema='work_shop')
    op.drop_column('work_shop', 'username', schema='work_shop')
    # ### end Alembic commands ###
