"""add access_token column to token

Revision ID: 0f517ad316f9
Revises: e52e9111db30
Create Date: 2025-10-11 20:50:44.936088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f517ad316f9'
down_revision: Union[str, Sequence[str], None] = 'e52e9111db30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cars'
    )
    op.create_index(op.f('ix_cars_cars_id'), 'cars', ['id'], unique=False, schema='cars')
    op.create_table('type_work_parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_work_parent_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cars'
    )
    op.create_index(op.f('ix_cars_type_work_parents_id'), 'type_work_parents', ['id'], unique=False, schema='cars')
    op.create_table('work_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_shop_name', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=False),
    sa.Column('street_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('username', sa.String(), server_default='', nullable=False),
    sa.Column('hash_password', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='work_shop'
    )
    op.create_index(op.f('ix_work_shop_work_shop_id'), 'work_shop', ['id'], unique=False, schema='work_shop')
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('id_work_shop', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_work_shop'], ['work_shop.work_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('type_work_children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_work_child_name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['cars.type_work_parents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cars'
    )
    op.create_index(op.f('ix_cars_type_work_children_id'), 'type_work_children', ['id'], unique=False, schema='cars')
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_shop_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=100), nullable=True),
    sa.Column('client_phone', sa.String(length=20), nullable=True),
    sa.Column('car_license_plate', sa.String(length=10), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=True),
    sa.Column('appointment_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['work_shop_id'], ['work_shop.work_shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='participants'
    )
    op.create_index(op.f('ix_participants_appointments_id'), 'appointments', ['id'], unique=False, schema='participants')
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('vin', sa.Numeric(), nullable=True),
    sa.Column('car_is', sa.String(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='participants'
    )
    op.create_index(op.f('ix_participants_participants_id'), 'participants', ['id'], unique=False, schema='participants')
    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_name', sa.String(), nullable=True),
    sa.Column('id_work_shop', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_work_shop'], ['work_shop.work_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streets_id'), 'streets', ['id'], unique=False)
    op.create_table('token',
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('work_shop_username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['work_shop_username'], ['work_shop.work_shop.username'], ),
    sa.PrimaryKeyConstraint('access_token')
    )
    op.create_table('avialable_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_name', sa.String(), nullable=True),
    sa.Column('work_shop_id', sa.Integer(), nullable=True),
    sa.Column('cars_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cars_id'], ['cars.cars.id'], ),
    sa.ForeignKeyConstraint(['work_shop_id'], ['work_shop.work_shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='work_shop'
    )
    op.create_index(op.f('ix_work_shop_avialable_cars_id'), 'avialable_cars', ['id'], unique=False, schema='work_shop')
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_shop_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['work_shop_id'], ['work_shop.work_shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='work_shop'
    )
    op.create_index(op.f('ix_work_shop_holidays_id'), 'holidays', ['id'], unique=False, schema='work_shop')
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('id_work_shop', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_work_shop'], ['work_shop.work_shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='work_shop'
    )
    op.create_index(op.f('ix_work_shop_photos_id'), 'photos', ['id'], unique=False, schema='work_shop')
    op.create_table('working_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_shop_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('is_working', sa.Boolean(), nullable=True),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['work_shop_id'], ['work_shop.work_shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='work_shop'
    )
    op.create_index(op.f('ix_work_shop_working_hours_id'), 'working_hours', ['id'], unique=False, schema='work_shop')
    op.create_table('appointments_cars',
    sa.Column('appointments_id', sa.Integer(), nullable=True),
    sa.Column('cars_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appointments_id'], ['participants.appointments.id'], ),
    sa.ForeignKeyConstraint(['cars_id'], ['cars.cars.id'], ),
    schema='participants'
    )
    op.create_table('appointments_work_shop',
    sa.Column('appointments_id', sa.Integer(), nullable=True),
    sa.Column('work_shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appointments_id'], ['participants.appointments.id'], ),
    sa.ForeignKeyConstraint(['work_shop_id'], ['work_shop.work_shop.id'], ),
    schema='participants'
    )
    op.create_table('appointments_work_type_children',
    sa.Column('appointments_id', sa.Integer(), nullable=True),
    sa.Column('work_type_children_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appointments_id'], ['participants.appointments.id'], ),
    sa.ForeignKeyConstraint(['work_type_children_id'], ['cars.type_work_children.id'], ),
    schema='participants'
    )
    op.create_table('holidays_work_shops',
    sa.Column('holidays_id', sa.Integer(), nullable=True),
    sa.Column('work_shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['holidays_id'], ['work_shop.holidays.id'], ),
    sa.ForeignKeyConstraint(['work_shop_id'], ['work_shop.work_shop.id'], ),
    schema='work_shop'
    )
    op.create_table('working_hour_work_shop',
    sa.Column('working_hour_id', sa.Integer(), nullable=True),
    sa.Column('work_shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['work_shop_id'], ['work_shop.work_shop.id'], ),
    sa.ForeignKeyConstraint(['working_hour_id'], ['work_shop.working_hours.id'], ),
    schema='work_shop'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('working_hour_work_shop', schema='work_shop')
    op.drop_table('holidays_work_shops', schema='work_shop')
    op.drop_table('appointments_work_type_children', schema='participants')
    op.drop_table('appointments_work_shop', schema='participants')
    op.drop_table('appointments_cars', schema='participants')
    op.drop_index(op.f('ix_work_shop_working_hours_id'), table_name='working_hours', schema='work_shop')
    op.drop_table('working_hours', schema='work_shop')
    op.drop_index(op.f('ix_work_shop_photos_id'), table_name='photos', schema='work_shop')
    op.drop_table('photos', schema='work_shop')
    op.drop_index(op.f('ix_work_shop_holidays_id'), table_name='holidays', schema='work_shop')
    op.drop_table('holidays', schema='work_shop')
    op.drop_index(op.f('ix_work_shop_avialable_cars_id'), table_name='avialable_cars', schema='work_shop')
    op.drop_table('avialable_cars', schema='work_shop')
    op.drop_table('token')
    op.drop_index(op.f('ix_streets_id'), table_name='streets')
    op.drop_table('streets')
    op.drop_index(op.f('ix_participants_participants_id'), table_name='participants', schema='participants')
    op.drop_table('participants', schema='participants')
    op.drop_index(op.f('ix_participants_appointments_id'), table_name='appointments', schema='participants')
    op.drop_table('appointments', schema='participants')
    op.drop_index(op.f('ix_cars_type_work_children_id'), table_name='type_work_children', schema='cars')
    op.drop_table('type_work_children', schema='cars')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_work_shop_work_shop_id'), table_name='work_shop', schema='work_shop')
    op.drop_table('work_shop', schema='work_shop')
    op.drop_index(op.f('ix_cars_type_work_parents_id'), table_name='type_work_parents', schema='cars')
    op.drop_table('type_work_parents', schema='cars')
    op.drop_index(op.f('ix_cars_cars_id'), table_name='cars', schema='cars')
    op.drop_table('cars', schema='cars')
    # ### end Alembic commands ###
