"""update work_shop

Revision ID: 30443cf7a7f1
Revises: ea2e1e108d35
Create Date: 2025-10-10 15:26:47.632742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30443cf7a7f1'
down_revision: Union[str, Sequence[str], None] = 'ea2e1e108d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('hash_token', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('id_work_shop', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_work_shop'], ['work_shop.work_shop.id'], ),
    sa.PrimaryKeyConstraint('hash_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth')
    # ### end Alembic commands ###
