"""appointments

Revision ID: 50ec97ec30ae
Revises: 0f517ad316f9
Create Date: 2025-10-12 10:25:49.731167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ec97ec30ae'
down_revision: Union[str, Sequence[str], None] = '0f517ad316f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('work_shop_username', sa.String(), nullable=True), schema='participants')
    op.drop_constraint(op.f('appointments_work_shop_id_fkey'), 'appointments', schema='participants', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'work_shop', ['work_shop_username'], ['username'], source_schema='participants', referent_schema='work_shop')
    op.drop_column('appointments', 'work_shop_id', schema='participants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('work_shop_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='participants')
    op.drop_constraint(None, 'appointments', schema='participants', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_work_shop_id_fkey'), 'appointments', 'work_shop', ['work_shop_id'], ['id'], source_schema='participants', referent_schema='work_shop')
    op.drop_column('appointments', 'work_shop_username', schema='participants')
    # ### end Alembic commands ###
