"""add login 

Revision ID: 579b8737e664
Revises: dbac5e2b7ad1
Create Date: 2025-10-09 16:18:55.701679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579b8737e664'
down_revision: Union[str, Sequence[str], None] = 'dbac5e2b7ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_shop', sa.Column('login', sa.String(), server_default='', nullable=False), schema='work_shop')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_shop', 'login', schema='work_shop')
    # ### end Alembic commands ###
