"""init

Revision ID: 766cf6cbc709
Revises: 
Create Date: 2025-09-26 01:33:40.604378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766cf6cbc709'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sto', 'address',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('sto', 'rating',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sto', 'rating',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('sto', 'address',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    # ### end Alembic commands ###
