"""change cars and participants

Revision ID: 8978316e385f
Revises: be70061a9eb4
Create Date: 2025-10-04 00:08:46.315658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8978316e385f'
down_revision: Union[str, Sequence[str], None] = 'be70061a9eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('email', sa.String(), nullable=False), schema='participants')
    op.add_column('participants', sa.Column('car_is', sa.String(), nullable=True), schema='participants')
    op.alter_column('participants', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='participants')
    op.drop_column('participants', 'name', schema='participants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True), schema='participants')
    op.alter_column('participants', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='participants')
    op.drop_column('participants', 'car_is', schema='participants')
    op.drop_column('participants', 'email', schema='participants')
    # ### end Alembic commands ###
