"""Second

Revision ID: bc8fc985d921
Revises: 710c9ed628ac
Create Date: 2025-10-03 23:37:25.963709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8fc985d921'
down_revision: Union[str, Sequence[str], None] = '710c9ed628ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('poly', sa.String(), nullable=True), schema='participants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'poly', schema='participants')
    # ### end Alembic commands ###
