"""Delete poly

Revision ID: be70061a9eb4
Revises: bc8fc985d921
Create Date: 2025-10-03 23:38:55.719430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be70061a9eb4'
down_revision: Union[str, Sequence[str], None] = 'bc8fc985d921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'poly', schema='participants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('poly', sa.VARCHAR(), autoincrement=False, nullable=True), schema='participants')
    # ### end Alembic commands ###
