"""update work_shop

Revision ID: d378929624d4
Revises: 30443cf7a7f1
Create Date: 2025-10-10 15:30:05.072079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd378929624d4'
down_revision: Union[str, Sequence[str], None] = '30443cf7a7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('hash_token', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('id_work_shop', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_work_shop'], ['work_shop.work_shop.id'], ),
    sa.PrimaryKeyConstraint('hash_token')
    )
    op.drop_table('auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('hash_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id_work_shop', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_work_shop'], ['work_shop.work_shop.id'], name=op.f('auth_id_work_shop_fkey')),
    sa.PrimaryKeyConstraint('hash_token', name=op.f('auth_pkey'))
    )
    op.drop_table('token')
    # ### end Alembic commands ###
