"""hash password

Revision ID: dbac5e2b7ad1
Revises: 8978316e385f
Create Date: 2025-10-08 13:46:03.222836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbac5e2b7ad1'
down_revision: Union[str, Sequence[str], None] = '8978316e385f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_shop', sa.Column('hash_password', sa.String(), nullable=False, server_default=''), schema='work_shop')
    op.alter_column('work_shop', 'work_shop_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='work_shop')
    op.alter_column('work_shop', 'telephone',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='work_shop')
    op.alter_column('work_shop', 'street_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='work_shop')
    op.alter_column('work_shop', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='work_shop')
    op.alter_column('work_shop', 'site',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='work_shop')
    op.alter_column('work_shop', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               schema='work_shop')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_shop', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               schema='work_shop')
    op.alter_column('work_shop', 'site',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='work_shop')
    op.alter_column('work_shop', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='work_shop')
    op.alter_column('work_shop', 'street_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='work_shop')
    op.alter_column('work_shop', 'telephone',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='work_shop')
    op.alter_column('work_shop', 'work_shop_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='work_shop')
    op.drop_column('work_shop', 'hash_password', schema='work_shop')
    # ### end Alembic commands ###
